In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [ ]:
base = pd.read_csv("/content/drive/MyDrive/mt_cars.csv", keep_default_na=False)

In [ ]:
base.head()

Unnamed: 0   mpg  cyl   disp   hp  ...   qsec  vs  am  gear  carb
0          Mazda RX4  21.0    6  160.0  110  ...  16.46   0   1     4     4
1      Mazda RX4 Wag  21.0    6  160.0  110  ...  17.02   0   1     4     4
2         Datsun 710  22.8    4  108.0   93  ...  18.61   1   1     4     1
3     Hornet 4 Drive  21.4    6  258.0  110  ...  19.44   1   0     3     1
4  Hornet Sportabout  18.7    8  360.0  175  ...  17.02   0   0     3     2

[5 rows x 12 columns]

In [ ]:
x = base[['mpg', 'hp']].values
y = base['cyl'].values

In [ ]:
knn = KNeighborsClassifier(n_neighbors=3)
model = knn.fit(x, y)

In [ ]:
y_predict = model.predict(x)
print(y_predict)

[6 6 4 6 8 6 8 4 4 6 6 8 8 8 8 8 8 4 4 4 4 8 8 8 8 4 4 4 8 8 8 6]


In [ ]:
accuracy = accuracy_score(y, y_predict)
precision = precision_score(y, y_predict, average='weighted')
recall = recall_score(y, y_predict, average='weighted')
f1 = f1_score(y, y_predict, average='weighted')
cm = confusion_matrix(y, y_predict)

print(f'Acurácia: {accuracy}')
print(f'Precisão: {precision}')
print(f'Recall: {recall}')
print(f'F1: {f1}')
print('Matriz de confusão:\n', cm)

Acurácia: 0.9375
Precisão: 0.9395833333333333
Recall: 0.9375
F1: 0.9372947454844006
Matriz de confusão:
 [[10  1  0]
 [ 0  6  1]
 [ 0  0 14]]


In [ ]:
new_data = np.array([[19.3, 105]])
predict = model.predict(new_data)
print(predict)

[6]


In [ ]:
distance, index = model.kneighbors(new_data)
print(distance)
print(index)

[[1.2        4.5177428  5.28109837]]
[[ 5 31  1]]


In [ ]:
base.loc[[1, 5, 31], ['mpg', 'hp', 'cyl']]

mpg   hp  cyl
1   21.0  110    6
5   18.1  105    6
31  21.4  109    4